/*  Smart Parking Access & Space Allocation Reasoning System
    CT-351 Knowledge Representation & Reasoning, NED University

    Generated by tools/build_all.py from krr/knowledge_base. Edit the
    Python sources, not this file.
    Scenario: morning_rush (Main demo: morning rush at 10:00)

    Run:   swipl prolog/smart_parking.pl
    Try:   ?- allocate(X, S).
           ?- can_allocate(fatima, S).
           ?- authorized_driver(usman).
           ?- show_allocations.
           ?- consistent.
*/

:- dynamic accessibility_badge/2, allocate/2, authorized/2, authorized_driver/1, can_allocate/2, current_date/1, current_hour/1, double_booked/1, eligible_for_space/2, employee/1, faculty/1, fits/2, grants/2, has_permit/2, holds_reservation/2, located_in/2, loses/2, open_type/1, owns/2, parking_facility/1, parking_space/1, parking_zone/1, part_of/2, permit/1, permit_class/2, permit_expiry/2, permit_matches_role/2, permit_start/2, permit_status/2, permit_valid/1, person/1, priority/2, requests/3, reservation/1, reservation_date/2, reserved_by/2, reserved_space/2, space_free/1, space_status/2, space_type/2, staff/1, student/1, suitable_space/2, vehicle/1, vehicle_type/2, visitor/1, zone_access/2, zone_closes/2, zone_open/1, zone_opens/2, zone_type/2.
:- discontiguous accessibility_badge/2, allocate/2, authorized/2, authorized_driver/1, can_allocate/2, current_date/1, current_hour/1, double_booked/1, eligible_for_space/2, employee/1, faculty/1, fits/2, grants/2, has_permit/2, holds_reservation/2, located_in/2, loses/2, open_type/1, owns/2, parking_facility/1, parking_space/1, parking_zone/1, part_of/2, permit/1, permit_class/2, permit_expiry/2, permit_matches_role/2, permit_start/2, permit_status/2, permit_valid/1, person/1, priority/2, requests/3, reservation/1, reservation_date/2, reserved_by/2, reserved_space/2, space_free/1, space_status/2, space_type/2, staff/1, student/1, suitable_space/2, vehicle/1, vehicle_type/2, visitor/1, zone_access/2, zone_closes/2, zone_open/1, zone_opens/2, zone_type/2.

% ---- Facts: People and roles --------------------------------------------
student(ali).
student(sara).
student(usman).
student(zara).
faculty(ahmed).
staff(fatima).
visitor(bilal).
visitor(hina).
accessibility_badge(ahmed, no).
accessibility_badge(ali, no).
accessibility_badge(bilal, no).
accessibility_badge(fatima, no).
accessibility_badge(hina, no).
accessibility_badge(sara, yes).
accessibility_badge(usman, no).
accessibility_badge(zara, no).

% ---- Facts: Vehicles and ownership --------------------------------------
vehicle(bike_fatima).
vehicle(car_ali).
vehicle(car_bilal).
vehicle(car_hina).
vehicle(car_sara).
vehicle(car_usman).
vehicle(car_zara).
vehicle(ev_ahmed).
owns(ahmed, ev_ahmed).
owns(ali, car_ali).
owns(bilal, car_bilal).
owns(fatima, bike_fatima).
owns(hina, car_hina).
owns(sara, car_sara).
owns(usman, car_usman).
owns(zara, car_zara).
vehicle_type(bike_fatima, motorbike).
vehicle_type(car_ali, car).
vehicle_type(car_bilal, car).
vehicle_type(car_hina, car).
vehicle_type(car_sara, car).
vehicle_type(car_usman, car).
vehicle_type(car_zara, car).
vehicle_type(ev_ahmed, electric_car).

% ---- Facts: Permits -----------------------------------------------------
permit(p_ahmed).
permit(p_ali).
permit(p_fatima).
permit(p_sara).
permit(p_usman).
permit(p_zara).
permit(vp_bilal).
has_permit(ahmed, p_ahmed).
has_permit(ali, p_ali).
has_permit(bilal, vp_bilal).
has_permit(fatima, p_fatima).
has_permit(sara, p_sara).
has_permit(usman, p_usman).
has_permit(zara, p_zara).
permit_class(p_ahmed, employee_permit).
permit_class(p_ali, student_permit).
permit_class(p_fatima, employee_permit).
permit_class(p_sara, student_permit).
permit_class(p_usman, student_permit).
permit_class(p_zara, student_permit).
permit_class(vp_bilal, visitor_pass).
permit_status(p_ahmed, active).
permit_status(p_ali, active).
permit_status(p_fatima, active).
permit_status(p_sara, active).
permit_status(p_usman, active).
permit_status(p_zara, active).
permit_status(vp_bilal, active).
permit_start(p_ahmed, 20260101).
permit_start(p_ali, 20260701).
permit_start(p_fatima, 20260101).
permit_start(p_sara, 20260701).
permit_start(p_usman, 20250916).
permit_start(p_zara, 20260701).
permit_start(vp_bilal, 20261002).
permit_expiry(p_ahmed, 20271231).
permit_expiry(p_ali, 20270630).
permit_expiry(p_fatima, 20271231).
permit_expiry(p_sara, 20270630).
permit_expiry(p_usman, 20260915).
permit_expiry(p_zara, 20270630).
permit_expiry(vp_bilal, 20261002).

% ---- Facts: Facility and zones ------------------------------------------
parking_facility(ned_lot).
parking_zone(zone_a).
parking_zone(zone_e).
parking_zone(zone_v).
part_of(zone_a, ned_lot).
part_of(zone_e, ned_lot).
part_of(zone_v, ned_lot).
zone_type(zone_a, student_zone).
zone_type(zone_e, employee_zone).
zone_type(zone_v, visitor_zone).
zone_opens(zone_a, 7).
zone_opens(zone_e, 6).
zone_opens(zone_v, 8).
zone_closes(zone_a, 22).
zone_closes(zone_e, 23).
zone_closes(zone_v, 17).

% ---- Facts: Parking spaces ----------------------------------------------
parking_space(s_a1).
parking_space(s_a2).
parking_space(s_a3).
parking_space(s_a4).
parking_space(s_a5).
parking_space(s_e1).
parking_space(s_e2).
parking_space(s_e3).
parking_space(s_v1).
located_in(s_a1, zone_a).
located_in(s_a2, zone_a).
located_in(s_a3, zone_a).
located_in(s_a4, zone_a).
located_in(s_a5, zone_a).
located_in(s_e1, zone_e).
located_in(s_e2, zone_e).
located_in(s_e3, zone_e).
located_in(s_v1, zone_v).
space_type(s_a1, standard).
space_type(s_a2, standard).
space_type(s_a3, accessible).
space_type(s_a4, motorbike).
space_type(s_a5, standard).
space_type(s_e1, standard).
space_type(s_e2, ev_charging).
space_type(s_e3, standard).
space_type(s_v1, standard).
space_status(s_a1, vacant).
space_status(s_a2, occupied).
space_status(s_a3, vacant).
space_status(s_a4, vacant).
space_status(s_a5, reserved).
space_status(s_e1, vacant).
space_status(s_e2, vacant).
space_status(s_e3, reserved).
space_status(s_v1, vacant).

% ---- Facts: Reservations ------------------------------------------------
reservation(r1).
reservation(r2).
reserved_by(r1, zara).
reserved_by(r2, ahmed).
reserved_space(r1, s_a5).
reserved_space(r2, s_e3).
reservation_date(r1, 20261002).
reservation_date(r2, 20261002).

% ---- Facts: Policy tables -----------------------------------------------
grants(employee_permit, employee_zone).
grants(student_permit, student_zone).
grants(visitor_pass, visitor_zone).
fits(car, accessible).
fits(car, standard).
fits(electric_car, accessible).
fits(electric_car, ev_charging).
fits(electric_car, standard).
fits(motorbike, motorbike).
open_type(ev_charging).
open_type(motorbike).
open_type(standard).

% ---- Facts: Context (per scenario) --------------------------------------
current_date(20261002).
current_hour(10).
requests(ahmed, s_e3, 800).
requests(ali, s_a1, 905).
requests(bilal, s_v1, 920).
requests(fatima, s_e1, 830).
requests(hina, s_v1, 915).
requests(sara, s_a1, 910).
requests(usman, s_a1, 900).
requests(zara, s_a1, 850).

% ---- Rules (Horn clauses) ----------------------------------------

% A. Class hierarchy
% R01: Every student is a person.
person(X) :- student(X).
% R02: Every employee is a person.
person(X) :- employee(X).
% R03: Every visitor is a person.
person(X) :- visitor(X).
% R04: Every faculty member is an employee.
employee(X) :- faculty(X).
% R05: Every staff member is an employee.
employee(X) :- staff(X).

% B. Permits and authorization
% R06: A permit is valid if its status is active and today lies between its start date and its expiry date.
permit_valid(P) :- permit_status(P, active), permit_start(P, B), permit_expiry(P, E), current_date(D), B =< D, E >= D.
% R07: A student permit only counts when its holder is a student.
permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, student_permit), student(X).
% R08: An employee permit only counts when its holder is faculty or staff.
permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, employee_permit), employee(X).
% R09: A visitor needs a visitor pass; the pass is the visitor's authorization.
permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, visitor_pass), visitor(X).
% R10: A person is authorized by a permit that matches their role and is valid.
authorized(X, P) :- permit_matches_role(X, P), permit_valid(P).
% R11: Anyone authorized by at least one permit is an authorized driver.
authorized_driver(X) :- authorized(X, P).

% C. Zones and time
% R12: A zone is open when the current hour is inside its opening hours.
zone_open(Z) :- zone_opens(Z, O), zone_closes(Z, C), current_hour(H), H >= O, H < C.
% R13: An authorized person may enter a zone if their permit class grants that zone type and the zone is open.
zone_access(X, Z) :- authorized(X, P), permit_class(P, C), grants(C, T), zone_type(Z, T), zone_open(Z).

% D. Suitability and eligibility
% R14: A space suits a person if it is in a zone they may enter and their vehicle fits the bay.
suitable_space(X, S) :- zone_access(X, Z), located_in(S, Z), owns(X, V), vehicle_type(V, VT), space_type(S, ST), fits(VT, ST).
% R15: A suitable standard, EV or motorbike bay needs nothing more.
eligible_for_space(X, S) :- suitable_space(X, S), space_type(S, T), open_type(T).
% R16: An accessible bay is only for a person who holds an accessibility badge.
eligible_for_space(X, S) :- suitable_space(X, S), space_type(S, accessible), accessibility_badge(X, yes).

% E. Availability and allocation
% R17: A vacant space is free.
space_free(S) :- space_status(S, vacant).
% R18: A person holds a reservation for a space if they made a reservation for it for today.
holds_reservation(X, S) :- reserved_by(R, X), reserved_space(R, S), reservation_date(R, D), current_date(D).
% R19: A free space can be allocated to any person eligible for it.
can_allocate(X, S) :- eligible_for_space(X, S), space_free(S).
% R20: A reserved space can be allocated only to the person holding today's reservation.
can_allocate(X, S) :- eligible_for_space(X, S), space_status(S, reserved), holds_reservation(X, S).

% F. Priority
% R21: Badge holders have priority 3 (highest).
priority(X, 3) :- person(X), accessibility_badge(X, yes).
% R22: Faculty and staff without a badge have priority 2.
priority(X, 2) :- employee(X), accessibility_badge(X, no).
% R23: Students without a badge have priority 1.
priority(X, 1) :- student(X), accessibility_badge(X, no).
% R24: Visitors without a badge have priority 1.
priority(X, 1) :- visitor(X), accessibility_badge(X, no).

% G. Conflicts
% R25: A requester loses a space to another eligible requester with higher priority.
loses(Y, S) :- requests(Y, S, TY), requests(X, S, TX), X \= Y, can_allocate(X, S), priority(X, PX), priority(Y, PY), PX > PY.
% R26: With equal priority, the earlier request wins (first come, first served).
loses(Y, S) :- requests(Y, S, TY), requests(X, S, TX), X \= Y, can_allocate(X, S), priority(X, P), priority(Y, P), TX < TY.
% R27: A person holding two different reservations for the same day is double-booked.
double_booked(X) :- reserved_by(R1, X), reserved_by(R2, X), R1 \= R2, reservation_date(R1, D), reservation_date(R2, D).

% H. Decision
% R28: Allocate the requested space if it can be allocated, the requester loses no conflict for it and is not double-booked.
allocate(X, S) :- requests(X, S, T), can_allocate(X, S), \+ loses(X, S), \+ double_booked(X).

% ---- Integrity constraints (denial clauses) ----------------------
% A constraint is violated when its body can be proved.
% IC1: One space is never allocated to two people.
violation(ic1) :- allocate(X, S), allocate(Y, S), X \= Y.
% IC2: One person is never allocated two spaces.
violation(ic2) :- allocate(X, S1), allocate(X, S2), S1 \= S2.
% IC3: An occupied space is never allocated.
violation(ic3) :- allocate(X, S), space_status(S, occupied).
% IC4: Nobody is both a student and an employee (Student ⊓ Employee ⊑ ⊥).
violation(ic4) :- student(X), employee(X).
% IC5: Nobody is both a student and a visitor.
violation(ic5) :- student(X), visitor(X).
% IC6: Nobody is both an employee and a visitor.
violation(ic6) :- employee(X), visitor(X).
% IC7: Nobody is both faculty and staff.
violation(ic7) :- faculty(X), staff(X).

% ---- Helpers --------------------------------------------------
consistent :- \+ violation(_).
show_allocations :-
    forall(allocate(X, S), format("allocate(~w, ~w)~n", [X, S])).
