"""Export the data the project website shows, straight from the engines.

    python tools/build_site.py

Writes website/data.js (a plain script that sets window.KRR) and copies the
report figures and the PDF next to the page. Every decision, reason, proof and
count on the site comes from running the code, so the site cannot drift from it.
"""

from __future__ import annotations

import json
import shutil
import sys
import unittest
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from krr.core.terms import format_atom  # noqa: E402
from krr.knowledge_base.rules import CONSTRAINTS, RULES  # noqa: E402
from krr.knowledge_base.scenarios import MAIN, TEST_CASES  # noqa: E402
from krr.semantic_net.network import build_instance_network  # noqa: E402
from krr.site_export import requests_json, run_summary  # noqa: E402
from krr.system import run  # noqa: E402

SITE = ROOT / "website"
ROLES = ("faculty", "staff", "student", "visitor")


def facts(kb, pred):
    return sorted(kb.facts_for(pred), key=str)


def lot(kb) -> dict:
    zones = []
    for _, z in facts(kb, "parking_zone"):
        ztype = next(t for _, zz, t in facts(kb, "zone_type") if zz == z)
        opens = next(h for _, zz, h in facts(kb, "zone_opens") if zz == z)
        closes = next(h for _, zz, h in facts(kb, "zone_closes") if zz == z)
        zones.append({"id": z, "type": ztype, "opens": opens, "closes": closes, "bays": []})
    types = {s: t for _, s, t in facts(kb, "space_type")}
    status = {s: t for _, s, t in facts(kb, "space_status")}
    holder = {r: p for _, r, p in facts(kb, "reserved_by")}
    reserved = {s: holder[r] for _, r, s in facts(kb, "reserved_space")}
    for _, s, z in facts(kb, "located_in"):
        bay = {"id": s, "type": types.get(s, "standard"), "status": status.get(s, "vacant"),
               "reservedFor": reserved.get(s)}
        next(zz for zz in zones if zz["id"] == z)["bays"].append(bay)
    return {"zones": zones}


def drivers(kb) -> dict:
    out = {}
    vtype = {v: t for _, v, t in facts(kb, "vehicle_type")}
    badge = {p: b for _, p, b in facts(kb, "accessibility_badge")}
    for role in ROLES:
        for _, p in facts(kb, role):
            out[p] = {"role": role, "badge": badge.get(p) == "yes", "vehicle": None}
    for _, p, v in facts(kb, "owns"):
        if p in out:
            out[p]["vehicle"] = vtype.get(v, "car")
    return out


def network_json() -> dict:
    """The worked-example semantic network (Ali, Zara's reservation r1 and the
    values on the paths in report section 5.3), for the 3D view."""
    net = build_instance_network(["ali", "r1"])
    return {"nodes": [{"id": n, "kind": k} for n, k in net.nodes.items()],
            "edges": [{"s": e.source, "label": e.label, "t": e.target} for e in net.edges]}


def main() -> None:
    r = run("morning_rush")
    kb = r.kb
    requests = requests_json(r)

    firings = r.forward.firings
    cycles = []
    for c in r.forward.cycles:
        derived = [{"rule": f.rule.rid, "fact": format_atom(f.derived)}
                   for f in firings if f.cycle == c.number]
        cycles.append({"n": c.number, "stratum": c.stratum, "conflict": c.conflict_set,
                       "fired": c.fired, "rules": c.rules_fired, "derived": derived})

    tests = []
    for sc in TEST_CASES:
        rows = run(sc).check_expectations()
        title = sc.title.split("  ", 1)
        tests.append({"id": title[0], "title": title[-1].strip(), "description": sc.description,
                      "checks": len(rows),
                      "pass": all(exp == fw == bw for _, exp, fw, bw in rows),
                      "goals": [{"goal": g, "expected": e, "forward": f, "backward": b}
                                for g, e, f, b in rows]})

    unit_tests = unittest.defaultTestLoader.discover(str(ROOT / "tests")).countTestCases()
    data = {
        "date": MAIN.date, "hour": MAIN.hour, "run": run_summary(r, MAIN.date, MAIN.hour),
        "stats": {"facts": len(r.forward.initial), "rules": len(RULES),
                  "constraints": len(CONSTRAINTS), "derived": len(r.forward.derived),
                  "cycles": len(r.forward.cycles), "violations": len(r.forward.violations),
                  "tests": len(tests), "testsPassed": sum(t["pass"] for t in tests),
                  "unitTests": unit_tests},
        "lot": lot(kb), "drivers": drivers(kb), "requests": requests,
        "cycles": cycles, "testCases": tests,
        "rules": [{"id": x.rid, "text": x.text} for x in RULES],
        "network": network_json(),
    }
    SITE.mkdir(exist_ok=True)
    (SITE / "data.js").write_text(
        "// Generated by tools/build_site.py from the reasoning engine. Do not edit.\n"
        "window.KRR = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8")
    # The scenario clock runs the engine itself in the browser (Pyodide), so ship
    # the krr package as a zip next to the page.
    with zipfile.ZipFile(SITE / "engine.zip", "w", zipfile.ZIP_DEFLATED) as zf:
        for py in sorted((ROOT / "krr").rglob("*.py")):
            zf.write(py, py.relative_to(ROOT).as_posix())
    (SITE / "clock.json").unlink(missing_ok=True)
    (SITE / "assets").mkdir(exist_ok=True)
    for png in (ROOT / "docs" / "figures").glob("*.png"):
        shutil.copy2(png, SITE / "assets" / png.name)
    pdf = ROOT / "docs" / "report" / "Smart_Parking_KRR_CCP_Report.pdf"
    if pdf.exists():
        shutil.copy2(pdf, SITE / "assets" / pdf.name)
    print(f"wrote website/data.js: {len(requests)} requests, {len(cycles)} cycles, "
          f"{len(tests)} test cases; website/engine.zip")


if __name__ == "__main__":
    main()
