// Generated by tools/build_site.py from the reasoning engine. Do not edit.
window.KRR = {
 "date": 20261002,
 "hour": 10,
 "run": {
  "date": 20261002,
  "hour": 10,
  "facts": 164,
  "derived": 105,
  "fired": [
   35,
   11,
   10,
   17,
   14,
   9,
   6,
   0,
   3,
   0
  ]
 },
 "stats": {
  "facts": 164,
  "rules": 28,
  "constraints": 7,
  "derived": 105,
  "cycles": 10,
  "violations": 0,
  "tests": 12,
  "testsPassed": 12,
  "unitTests": 68
 },
 "lot": {
  "zones": [
   {
    "id": "zone_a",
    "type": "student_zone",
    "opens": 7,
    "closes": 22,
    "bays": [
     {
      "id": "s_a1",
      "type": "standard",
      "status": "vacant",
      "reservedFor": null
     },
     {
      "id": "s_a2",
      "type": "standard",
      "status": "occupied",
      "reservedFor": null
     },
     {
      "id": "s_a3",
      "type": "accessible",
      "status": "vacant",
      "reservedFor": null
     },
     {
      "id": "s_a4",
      "type": "motorbike",
      "status": "vacant",
      "reservedFor": null
     },
     {
      "id": "s_a5",
      "type": "standard",
      "status": "reserved",
      "reservedFor": "zara"
     }
    ]
   },
   {
    "id": "zone_e",
    "type": "employee_zone",
    "opens": 6,
    "closes": 23,
    "bays": [
     {
      "id": "s_e1",
      "type": "standard",
      "status": "vacant",
      "reservedFor": null
     },
     {
      "id": "s_e2",
      "type": "ev_charging",
      "status": "vacant",
      "reservedFor": null
     },
     {
      "id": "s_e3",
      "type": "standard",
      "status": "reserved",
      "reservedFor": "ahmed"
     }
    ]
   },
   {
    "id": "zone_v",
    "type": "visitor_zone",
    "opens": 8,
    "closes": 17,
    "bays": [
     {
      "id": "s_v1",
      "type": "standard",
      "status": "vacant",
      "reservedFor": null
     }
    ]
   }
  ]
 },
 "drivers": {
  "ahmed": {
   "role": "faculty",
   "badge": false,
   "vehicle": "electric_car"
  },
  "fatima": {
   "role": "staff",
   "badge": false,
   "vehicle": "motorbike"
  },
  "ali": {
   "role": "student",
   "badge": false,
   "vehicle": "car"
  },
  "sara": {
   "role": "student",
   "badge": true,
   "vehicle": "car"
  },
  "usman": {
   "role": "student",
   "badge": false,
   "vehicle": "car"
  },
  "zara": {
   "role": "student",
   "badge": false,
   "vehicle": "car"
  },
  "bilal": {
   "role": "visitor",
   "badge": false,
   "vehicle": "car"
  },
  "hina": {
   "role": "visitor",
   "badge": false,
   "vehicle": "car"
  }
 },
 "requests": [
  {
   "driver": "ahmed",
   "space": "s_e3",
   "time": 800,
   "goal": "allocate(ahmed, s_e3)",
   "allocated": true,
   "reasons": [],
   "proof": {
    "t": "allocate(ahmed, s_e3)",
    "how": "R28",
    "c": [
     {
      "t": "requests(ahmed, s_e3, 800)",
      "how": "fact",
      "c": []
     },
     {
      "t": "can_allocate(ahmed, s_e3)",
      "how": "R20",
      "c": [
       {
        "t": "eligible_for_space(ahmed, s_e3)",
        "how": "R15",
        "c": [
         {
          "t": "suitable_space(ahmed, s_e3)",
          "how": "R14",
          "c": [
           {
            "t": "zone_access(ahmed, zone_e)",
            "how": "R13",
            "c": [
             {
              "t": "authorized(ahmed, p_ahmed)",
              "how": "R10",
              "c": [
               {
                "t": "permit_matches_role(ahmed, p_ahmed)",
                "how": "R08",
                "c": [
                 {
                  "t": "has_permit(ahmed, p_ahmed)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_class(p_ahmed, employee_permit)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "employee(ahmed)",
                  "how": "R04",
                  "c": [
                   {
                    "t": "faculty(ahmed)",
                    "how": "fact",
                    "c": []
                   }
                  ]
                 }
                ]
               },
               {
                "t": "permit_valid(p_ahmed)",
                "how": "R06",
                "c": [
                 {
                  "t": "permit_status(p_ahmed, active)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_start(p_ahmed, 20260101)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_expiry(p_ahmed, 20271231)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "current_date(20261002)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "20260101 =< 20261002",
                  "how": "built-in",
                  "c": []
                 },
                 {
                  "t": "20271231 >= 20261002",
                  "how": "built-in",
                  "c": []
                 }
                ]
               }
              ]
             },
             {
              "t": "permit_class(p_ahmed, employee_permit)",
              "how": "fact",
              "c": []
             },
             {
              "t": "grants(employee_permit, employee_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_type(zone_e, employee_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_open(zone_e)",
              "how": "R12",
              "c": [
               {
                "t": "zone_opens(zone_e, 6)",
                "how": "fact",
                "c": []
               },
               {
                "t": "zone_closes(zone_e, 23)",
                "how": "fact",
                "c": []
               },
               {
                "t": "current_hour(10)",
                "how": "fact",
                "c": []
               },
               {
                "t": "10 >= 6",
                "how": "built-in",
                "c": []
               },
               {
                "t": "10 < 23",
                "how": "built-in",
                "c": []
               }
              ]
             }
            ]
           },
           {
            "t": "located_in(s_e3, zone_e)",
            "how": "fact",
            "c": []
           },
           {
            "t": "owns(ahmed, ev_ahmed)",
            "how": "fact",
            "c": []
           },
           {
            "t": "vehicle_type(ev_ahmed, electric_car)",
            "how": "fact",
            "c": []
           },
           {
            "t": "space_type(s_e3, standard)",
            "how": "fact",
            "c": []
           },
           {
            "t": "fits(electric_car, standard)",
            "how": "fact",
            "c": []
           }
          ]
         },
         {
          "t": "space_type(s_e3, standard)",
          "how": "fact",
          "c": []
         },
         {
          "t": "open_type(standard)",
          "how": "fact",
          "c": []
         }
        ]
       },
       {
        "t": "space_status(s_e3, reserved)",
        "how": "fact",
        "c": []
       },
       {
        "t": "holds_reservation(ahmed, s_e3)",
        "how": "R18",
        "c": [
         {
          "t": "reserved_by(r2, ahmed)",
          "how": "fact",
          "c": []
         },
         {
          "t": "reserved_space(r2, s_e3)",
          "how": "fact",
          "c": []
         },
         {
          "t": "reservation_date(r2, 20261002)",
          "how": "fact",
          "c": []
         },
         {
          "t": "current_date(20261002)",
          "how": "fact",
          "c": []
         }
        ]
       }
      ]
     },
     {
      "t": "not loses(ahmed, s_e3)",
      "how": "negation as failure",
      "c": []
     },
     {
      "t": "not double_booked(ahmed)",
      "how": "negation as failure",
      "c": []
     }
    ]
   },
   "steps": 323
  },
  {
   "driver": "fatima",
   "space": "s_e1",
   "time": 830,
   "goal": "allocate(fatima, s_e1)",
   "allocated": false,
   "reasons": [
    "suitable_space(fatima, s_e1) fails at fits(motorbike, standard) (no such fact is stored)"
   ],
   "whyNot": {
    "goal": "allocate(fatima, s_e1)",
    "rule": "",
    "detail": "cannot be proved",
    "c": [
     {
      "goal": "can_allocate(fatima, s_e1)",
      "rule": "R28",
      "detail": "",
      "c": [
       {
        "goal": "eligible_for_space(fatima, s_e1)",
        "rule": "R19",
        "detail": "",
        "c": [
         {
          "goal": "suitable_space(fatima, s_e1)",
          "rule": "R15",
          "detail": "",
          "c": [
           {
            "goal": "fits(motorbike, standard)",
            "rule": "R14",
            "detail": "no such fact is stored",
            "c": []
           }
          ]
         },
         {
          "goal": "suitable_space(fatima, s_e1)",
          "rule": "R16",
          "detail": "explained above",
          "c": []
         }
        ]
       },
       {
        "goal": "eligible_for_space(fatima, s_e1)",
        "rule": "R20",
        "detail": "explained above",
        "c": []
       }
      ]
     }
    ]
   }
  },
  {
   "driver": "zara",
   "space": "s_a1",
   "time": 850,
   "goal": "allocate(zara, s_a1)",
   "allocated": false,
   "reasons": [
    "allocate(zara, s_a1) fails at not loses(zara, s_a1) (loses(zara, s_a1) is provable by R25; competing request: requests(sara, s_a1, 910))"
   ],
   "whyNot": {
    "goal": "allocate(zara, s_a1)",
    "rule": "",
    "detail": "cannot be proved",
    "c": [
     {
      "goal": "not loses(zara, s_a1)",
      "rule": "R28",
      "detail": "loses(zara, s_a1) is provable by R25; competing request: requests(sara, s_a1, 910)",
      "c": []
     }
    ]
   }
  },
  {
   "driver": "usman",
   "space": "s_a1",
   "time": 900,
   "goal": "allocate(usman, s_a1)",
   "allocated": false,
   "reasons": [
    "permit_valid(p_usman) fails at 20260915 >= 20261002 (false)"
   ],
   "whyNot": {
    "goal": "allocate(usman, s_a1)",
    "rule": "",
    "detail": "cannot be proved",
    "c": [
     {
      "goal": "can_allocate(usman, s_a1)",
      "rule": "R28",
      "detail": "",
      "c": [
       {
        "goal": "eligible_for_space(usman, s_a1)",
        "rule": "R19",
        "detail": "",
        "c": [
         {
          "goal": "suitable_space(usman, s_a1)",
          "rule": "R15",
          "detail": "",
          "c": [
           {
            "goal": "zone_access(usman, Z)",
            "rule": "R14",
            "detail": "",
            "c": [
             {
              "goal": "authorized(usman, P)",
              "rule": "R13",
              "detail": "",
              "c": [
               {
                "goal": "permit_valid(p_usman)",
                "rule": "R10",
                "detail": "",
                "c": [
                 {
                  "goal": "20260915 >= 20261002",
                  "rule": "R06",
                  "detail": "false",
                  "c": []
                 }
                ]
               }
              ]
             }
            ]
           }
          ]
         },
         {
          "goal": "suitable_space(usman, s_a1)",
          "rule": "R16",
          "detail": "explained above",
          "c": []
         }
        ]
       },
       {
        "goal": "eligible_for_space(usman, s_a1)",
        "rule": "R20",
        "detail": "explained above",
        "c": []
       }
      ]
     }
    ]
   }
  },
  {
   "driver": "ali",
   "space": "s_a1",
   "time": 905,
   "goal": "allocate(ali, s_a1)",
   "allocated": false,
   "reasons": [
    "allocate(ali, s_a1) fails at not loses(ali, s_a1) (loses(ali, s_a1) is provable by R25; competing request: requests(sara, s_a1, 910))"
   ],
   "whyNot": {
    "goal": "allocate(ali, s_a1)",
    "rule": "",
    "detail": "cannot be proved",
    "c": [
     {
      "goal": "not loses(ali, s_a1)",
      "rule": "R28",
      "detail": "loses(ali, s_a1) is provable by R25; competing request: requests(sara, s_a1, 910)",
      "c": []
     }
    ]
   }
  },
  {
   "driver": "sara",
   "space": "s_a1",
   "time": 910,
   "goal": "allocate(sara, s_a1)",
   "allocated": true,
   "reasons": [],
   "proof": {
    "t": "allocate(sara, s_a1)",
    "how": "R28",
    "c": [
     {
      "t": "requests(sara, s_a1, 910)",
      "how": "fact",
      "c": []
     },
     {
      "t": "can_allocate(sara, s_a1)",
      "how": "R19",
      "c": [
       {
        "t": "eligible_for_space(sara, s_a1)",
        "how": "R15",
        "c": [
         {
          "t": "suitable_space(sara, s_a1)",
          "how": "R14",
          "c": [
           {
            "t": "zone_access(sara, zone_a)",
            "how": "R13",
            "c": [
             {
              "t": "authorized(sara, p_sara)",
              "how": "R10",
              "c": [
               {
                "t": "permit_matches_role(sara, p_sara)",
                "how": "R07",
                "c": [
                 {
                  "t": "has_permit(sara, p_sara)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_class(p_sara, student_permit)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "student(sara)",
                  "how": "fact",
                  "c": []
                 }
                ]
               },
               {
                "t": "permit_valid(p_sara)",
                "how": "R06",
                "c": [
                 {
                  "t": "permit_status(p_sara, active)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_start(p_sara, 20260701)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_expiry(p_sara, 20270630)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "current_date(20261002)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "20260701 =< 20261002",
                  "how": "built-in",
                  "c": []
                 },
                 {
                  "t": "20270630 >= 20261002",
                  "how": "built-in",
                  "c": []
                 }
                ]
               }
              ]
             },
             {
              "t": "permit_class(p_sara, student_permit)",
              "how": "fact",
              "c": []
             },
             {
              "t": "grants(student_permit, student_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_type(zone_a, student_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_open(zone_a)",
              "how": "R12",
              "c": [
               {
                "t": "zone_opens(zone_a, 7)",
                "how": "fact",
                "c": []
               },
               {
                "t": "zone_closes(zone_a, 22)",
                "how": "fact",
                "c": []
               },
               {
                "t": "current_hour(10)",
                "how": "fact",
                "c": []
               },
               {
                "t": "10 >= 7",
                "how": "built-in",
                "c": []
               },
               {
                "t": "10 < 22",
                "how": "built-in",
                "c": []
               }
              ]
             }
            ]
           },
           {
            "t": "located_in(s_a1, zone_a)",
            "how": "fact",
            "c": []
           },
           {
            "t": "owns(sara, car_sara)",
            "how": "fact",
            "c": []
           },
           {
            "t": "vehicle_type(car_sara, car)",
            "how": "fact",
            "c": []
           },
           {
            "t": "space_type(s_a1, standard)",
            "how": "fact",
            "c": []
           },
           {
            "t": "fits(car, standard)",
            "how": "fact",
            "c": []
           }
          ]
         },
         {
          "t": "space_type(s_a1, standard)",
          "how": "fact",
          "c": []
         },
         {
          "t": "open_type(standard)",
          "how": "fact",
          "c": []
         }
        ]
       },
       {
        "t": "space_free(s_a1)",
        "how": "R17",
        "c": [
         {
          "t": "space_status(s_a1, vacant)",
          "how": "fact",
          "c": []
         }
        ]
       }
      ]
     },
     {
      "t": "not loses(sara, s_a1)",
      "how": "negation as failure",
      "c": []
     },
     {
      "t": "not double_booked(sara)",
      "how": "negation as failure",
      "c": []
     }
    ]
   },
   "steps": 2240
  },
  {
   "driver": "hina",
   "space": "s_v1",
   "time": 915,
   "goal": "allocate(hina, s_v1)",
   "allocated": false,
   "reasons": [
    "permit_matches_role(hina, P) fails at has_permit(hina, P) (no such fact is stored)"
   ],
   "whyNot": {
    "goal": "allocate(hina, s_v1)",
    "rule": "",
    "detail": "cannot be proved",
    "c": [
     {
      "goal": "can_allocate(hina, s_v1)",
      "rule": "R28",
      "detail": "",
      "c": [
       {
        "goal": "eligible_for_space(hina, s_v1)",
        "rule": "R19",
        "detail": "",
        "c": [
         {
          "goal": "suitable_space(hina, s_v1)",
          "rule": "R15",
          "detail": "",
          "c": [
           {
            "goal": "zone_access(hina, Z)",
            "rule": "R14",
            "detail": "",
            "c": [
             {
              "goal": "authorized(hina, P)",
              "rule": "R13",
              "detail": "",
              "c": [
               {
                "goal": "permit_matches_role(hina, P)",
                "rule": "R10",
                "detail": "",
                "c": [
                 {
                  "goal": "has_permit(hina, P)",
                  "rule": "R07",
                  "detail": "no such fact is stored",
                  "c": []
                 },
                 {
                  "goal": "has_permit(hina, P)",
                  "rule": "R08",
                  "detail": "no such fact is stored",
                  "c": []
                 },
                 {
                  "goal": "has_permit(hina, P)",
                  "rule": "R09",
                  "detail": "no such fact is stored",
                  "c": []
                 }
                ]
               }
              ]
             }
            ]
           }
          ]
         },
         {
          "goal": "suitable_space(hina, s_v1)",
          "rule": "R16",
          "detail": "explained above",
          "c": []
         }
        ]
       },
       {
        "goal": "eligible_for_space(hina, s_v1)",
        "rule": "R20",
        "detail": "explained above",
        "c": []
       }
      ]
     }
    ]
   }
  },
  {
   "driver": "bilal",
   "space": "s_v1",
   "time": 920,
   "goal": "allocate(bilal, s_v1)",
   "allocated": true,
   "reasons": [],
   "proof": {
    "t": "allocate(bilal, s_v1)",
    "how": "R28",
    "c": [
     {
      "t": "requests(bilal, s_v1, 920)",
      "how": "fact",
      "c": []
     },
     {
      "t": "can_allocate(bilal, s_v1)",
      "how": "R19",
      "c": [
       {
        "t": "eligible_for_space(bilal, s_v1)",
        "how": "R15",
        "c": [
         {
          "t": "suitable_space(bilal, s_v1)",
          "how": "R14",
          "c": [
           {
            "t": "zone_access(bilal, zone_v)",
            "how": "R13",
            "c": [
             {
              "t": "authorized(bilal, vp_bilal)",
              "how": "R10",
              "c": [
               {
                "t": "permit_matches_role(bilal, vp_bilal)",
                "how": "R09",
                "c": [
                 {
                  "t": "has_permit(bilal, vp_bilal)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_class(vp_bilal, visitor_pass)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "visitor(bilal)",
                  "how": "fact",
                  "c": []
                 }
                ]
               },
               {
                "t": "permit_valid(vp_bilal)",
                "how": "R06",
                "c": [
                 {
                  "t": "permit_status(vp_bilal, active)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_start(vp_bilal, 20261002)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "permit_expiry(vp_bilal, 20261002)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "current_date(20261002)",
                  "how": "fact",
                  "c": []
                 },
                 {
                  "t": "20261002 =< 20261002",
                  "how": "built-in",
                  "c": []
                 },
                 {
                  "t": "20261002 >= 20261002",
                  "how": "built-in",
                  "c": []
                 }
                ]
               }
              ]
             },
             {
              "t": "permit_class(vp_bilal, visitor_pass)",
              "how": "fact",
              "c": []
             },
             {
              "t": "grants(visitor_pass, visitor_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_type(zone_v, visitor_zone)",
              "how": "fact",
              "c": []
             },
             {
              "t": "zone_open(zone_v)",
              "how": "R12",
              "c": [
               {
                "t": "zone_opens(zone_v, 8)",
                "how": "fact",
                "c": []
               },
               {
                "t": "zone_closes(zone_v, 17)",
                "how": "fact",
                "c": []
               },
               {
                "t": "current_hour(10)",
                "how": "fact",
                "c": []
               },
               {
                "t": "10 >= 8",
                "how": "built-in",
                "c": []
               },
               {
                "t": "10 < 17",
                "how": "built-in",
                "c": []
               }
              ]
             }
            ]
           },
           {
            "t": "located_in(s_v1, zone_v)",
            "how": "fact",
            "c": []
           },
           {
            "t": "owns(bilal, car_bilal)",
            "how": "fact",
            "c": []
           },
           {
            "t": "vehicle_type(car_bilal, car)",
            "how": "fact",
            "c": []
           },
           {
            "t": "space_type(s_v1, standard)",
            "how": "fact",
            "c": []
           },
           {
            "t": "fits(car, standard)",
            "how": "fact",
            "c": []
           }
          ]
         },
         {
          "t": "space_type(s_v1, standard)",
          "how": "fact",
          "c": []
         },
         {
          "t": "open_type(standard)",
          "how": "fact",
          "c": []
         }
        ]
       },
       {
        "t": "space_free(s_v1)",
        "how": "R17",
        "c": [
         {
          "t": "space_status(s_v1, vacant)",
          "how": "fact",
          "c": []
         }
        ]
       }
      ]
     },
     {
      "t": "not loses(bilal, s_v1)",
      "how": "negation as failure",
      "c": []
     },
     {
      "t": "not double_booked(bilal)",
      "how": "negation as failure",
      "c": []
     }
    ]
   },
   "steps": 374
  }
 ],
 "cycles": [
  {
   "n": 1,
   "stratum": 0,
   "conflict": 35,
   "fired": 35,
   "rules": [
    "R01",
    "R03",
    "R04",
    "R05",
    "R06",
    "R07",
    "R09",
    "R12",
    "R17",
    "R18",
    "R23",
    "R24"
   ],
   "derived": [
    {
     "rule": "R01",
     "fact": "person(sara)"
    },
    {
     "rule": "R01",
     "fact": "person(ali)"
    },
    {
     "rule": "R01",
     "fact": "person(usman)"
    },
    {
     "rule": "R01",
     "fact": "person(zara)"
    },
    {
     "rule": "R03",
     "fact": "person(bilal)"
    },
    {
     "rule": "R03",
     "fact": "person(hina)"
    },
    {
     "rule": "R04",
     "fact": "employee(ahmed)"
    },
    {
     "rule": "R05",
     "fact": "employee(fatima)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(p_zara)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(p_ahmed)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(vp_bilal)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(p_sara)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(p_fatima)"
    },
    {
     "rule": "R06",
     "fact": "permit_valid(p_ali)"
    },
    {
     "rule": "R07",
     "fact": "permit_matches_role(ali, p_ali)"
    },
    {
     "rule": "R07",
     "fact": "permit_matches_role(sara, p_sara)"
    },
    {
     "rule": "R07",
     "fact": "permit_matches_role(usman, p_usman)"
    },
    {
     "rule": "R07",
     "fact": "permit_matches_role(zara, p_zara)"
    },
    {
     "rule": "R09",
     "fact": "permit_matches_role(bilal, vp_bilal)"
    },
    {
     "rule": "R12",
     "fact": "zone_open(zone_v)"
    },
    {
     "rule": "R12",
     "fact": "zone_open(zone_e)"
    },
    {
     "rule": "R12",
     "fact": "zone_open(zone_a)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_a4)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_e2)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_a1)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_a3)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_v1)"
    },
    {
     "rule": "R17",
     "fact": "space_free(s_e1)"
    },
    {
     "rule": "R18",
     "fact": "holds_reservation(ahmed, s_e3)"
    },
    {
     "rule": "R18",
     "fact": "holds_reservation(zara, s_a5)"
    },
    {
     "rule": "R23",
     "fact": "priority(ali, 1)"
    },
    {
     "rule": "R23",
     "fact": "priority(usman, 1)"
    },
    {
     "rule": "R23",
     "fact": "priority(zara, 1)"
    },
    {
     "rule": "R24",
     "fact": "priority(bilal, 1)"
    },
    {
     "rule": "R24",
     "fact": "priority(hina, 1)"
    }
   ]
  },
  {
   "n": 2,
   "stratum": 0,
   "conflict": 46,
   "fired": 11,
   "rules": [
    "R02",
    "R08",
    "R10",
    "R21",
    "R22"
   ],
   "derived": [
    {
     "rule": "R02",
     "fact": "person(ahmed)"
    },
    {
     "rule": "R02",
     "fact": "person(fatima)"
    },
    {
     "rule": "R08",
     "fact": "permit_matches_role(fatima, p_fatima)"
    },
    {
     "rule": "R08",
     "fact": "permit_matches_role(ahmed, p_ahmed)"
    },
    {
     "rule": "R10",
     "fact": "authorized(bilal, vp_bilal)"
    },
    {
     "rule": "R10",
     "fact": "authorized(ali, p_ali)"
    },
    {
     "rule": "R10",
     "fact": "authorized(sara, p_sara)"
    },
    {
     "rule": "R10",
     "fact": "authorized(zara, p_zara)"
    },
    {
     "rule": "R21",
     "fact": "priority(sara, 3)"
    },
    {
     "rule": "R22",
     "fact": "priority(ahmed, 2)"
    },
    {
     "rule": "R22",
     "fact": "priority(fatima, 2)"
    }
   ]
  },
  {
   "n": 3,
   "stratum": 0,
   "conflict": 56,
   "fired": 10,
   "rules": [
    "R10",
    "R11",
    "R13"
   ],
   "derived": [
    {
     "rule": "R10",
     "fact": "authorized(fatima, p_fatima)"
    },
    {
     "rule": "R10",
     "fact": "authorized(ahmed, p_ahmed)"
    },
    {
     "rule": "R11",
     "fact": "authorized_driver(sara)"
    },
    {
     "rule": "R11",
     "fact": "authorized_driver(ali)"
    },
    {
     "rule": "R11",
     "fact": "authorized_driver(zara)"
    },
    {
     "rule": "R11",
     "fact": "authorized_driver(bilal)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(sara, zone_a)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(ali, zone_a)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(zara, zone_a)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(bilal, zone_v)"
    }
   ]
  },
  {
   "n": 4,
   "stratum": 0,
   "conflict": 73,
   "fired": 17,
   "rules": [
    "R11",
    "R13",
    "R14"
   ],
   "derived": [
    {
     "rule": "R11",
     "fact": "authorized_driver(fatima)"
    },
    {
     "rule": "R11",
     "fact": "authorized_driver(ahmed)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(fatima, zone_e)"
    },
    {
     "rule": "R13",
     "fact": "zone_access(ahmed, zone_e)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ali, s_a1)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ali, s_a3)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ali, s_a2)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ali, s_a5)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(sara, s_a1)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(sara, s_a3)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(sara, s_a2)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(sara, s_a5)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(zara, s_a1)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(zara, s_a3)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(zara, s_a2)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(zara, s_a5)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(bilal, s_v1)"
    }
   ]
  },
  {
   "n": 5,
   "stratum": 0,
   "conflict": 87,
   "fired": 14,
   "rules": [
    "R14",
    "R15",
    "R16"
   ],
   "derived": [
    {
     "rule": "R14",
     "fact": "suitable_space(ahmed, s_e2)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ahmed, s_e3)"
    },
    {
     "rule": "R14",
     "fact": "suitable_space(ahmed, s_e1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(ali, s_a5)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(sara, s_a1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(zara, s_a5)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(ali, s_a2)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(ali, s_a1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(sara, s_a5)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(zara, s_a2)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(zara, s_a1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(bilal, s_v1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(sara, s_a2)"
    },
    {
     "rule": "R16",
     "fact": "eligible_for_space(sara, s_a3)"
    }
   ]
  },
  {
   "n": 6,
   "stratum": 0,
   "conflict": 96,
   "fired": 9,
   "rules": [
    "R15",
    "R19",
    "R20"
   ],
   "derived": [
    {
     "rule": "R15",
     "fact": "eligible_for_space(ahmed, s_e1)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(ahmed, s_e2)"
    },
    {
     "rule": "R15",
     "fact": "eligible_for_space(ahmed, s_e3)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(zara, s_a1)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(sara, s_a3)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(bilal, s_v1)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(sara, s_a1)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(ali, s_a1)"
    },
    {
     "rule": "R20",
     "fact": "can_allocate(zara, s_a5)"
    }
   ]
  },
  {
   "n": 7,
   "stratum": 0,
   "conflict": 104,
   "fired": 6,
   "rules": [
    "R19",
    "R20",
    "R25"
   ],
   "derived": [
    {
     "rule": "R19",
     "fact": "can_allocate(ahmed, s_e1)"
    },
    {
     "rule": "R19",
     "fact": "can_allocate(ahmed, s_e2)"
    },
    {
     "rule": "R20",
     "fact": "can_allocate(ahmed, s_e3)"
    },
    {
     "rule": "R25",
     "fact": "loses(zara, s_a1)"
    },
    {
     "rule": "R25",
     "fact": "loses(usman, s_a1)"
    },
    {
     "rule": "R25",
     "fact": "loses(ali, s_a1)"
    }
   ]
  },
  {
   "n": 8,
   "stratum": 0,
   "conflict": 104,
   "fired": 0,
   "rules": [],
   "derived": []
  },
  {
   "n": 9,
   "stratum": 1,
   "conflict": 3,
   "fired": 3,
   "rules": [
    "R28"
   ],
   "derived": [
    {
     "rule": "R28",
     "fact": "allocate(bilal, s_v1)"
    },
    {
     "rule": "R28",
     "fact": "allocate(sara, s_a1)"
    },
    {
     "rule": "R28",
     "fact": "allocate(ahmed, s_e3)"
    }
   ]
  },
  {
   "n": 10,
   "stratum": 1,
   "conflict": 3,
   "fired": 0,
   "rules": [],
   "derived": []
  }
 ],
 "testCases": [
  {
   "id": "TC1",
   "title": "Valid student, valid permit, free student bay",
   "description": "Ali (student, permit valid until 30 Jun 2027) asks for the vacant bay s_a1 in the student zone.",
   "checks": 4,
   "pass": true,
   "goals": [
    {
     "goal": "authorized_driver(ali)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "eligible_for_space(ali, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "can_allocate(ali, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "allocate(ali, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    }
   ]
  },
  {
   "id": "TC2",
   "title": "Expired permit",
   "description": "Usman's student permit expired on 15 Sep 2026. Today is 2 Oct 2026.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "permit_valid(p_usman)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "authorized_driver(usman)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(usman, s_a1)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC3",
   "title": "Visitor without authorization",
   "description": "Hina is a visitor with no visitor pass. Bilal, also a visitor, has a pass for today.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "authorized_driver(hina)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(hina, s_v1)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "authorized_driver(bilal)",
     "expected": true,
     "forward": true,
     "backward": true
    }
   ]
  },
  {
   "id": "TC4",
   "title": "Space already occupied",
   "description": "Ali asks for s_a2, a student bay that is occupied.",
   "checks": 4,
   "pass": true,
   "goals": [
    {
     "goal": "eligible_for_space(ali, s_a2)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "space_free(s_a2)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "can_allocate(ali, s_a2)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(ali, s_a2)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC5",
   "title": "Student requests an employee-only space",
   "description": "Ali asks for s_e1 in the employee zone.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "authorized_driver(ali)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "zone_access(ali, zone_e)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(ali, s_e1)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC6",
   "title": "Eligible driver, but no suitable space",
   "description": "Fatima (staff) is authorized for the employee zone, but she rides a motorbike and the employee zone has no motorbike bay.",
   "checks": 4,
   "pass": true,
   "goals": [
    {
     "goal": "authorized_driver(fatima)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "zone_access(fatima, zone_e)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "suitable_space(fatima, s_e1)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(fatima, s_e1)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC7",
   "title": "Three drivers request the same space",
   "description": "Zara (08:50), Ali (09:05) and Sara (09:10, badge holder) all ask for s_a1. Sara has priority 3 and wins. Between Zara and Ali (both priority 1) the earlier request wins, so Ali also loses to Zara.",
   "checks": 5,
   "pass": true,
   "goals": [
    {
     "goal": "allocate(sara, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "loses(zara, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "loses(ali, s_a1)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "allocate(ali, s_a1)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(zara, s_a1)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC8",
   "title": "Accessible space requested by an ineligible driver",
   "description": "Ali has no accessibility badge and asks for the accessible bay s_a3. Sara, who holds a badge, is eligible for the same bay.",
   "checks": 4,
   "pass": true,
   "goals": [
    {
     "goal": "suitable_space(ali, s_a3)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "eligible_for_space(ali, s_a3)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(ali, s_a3)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "eligible_for_space(sara, s_a3)",
     "expected": true,
     "forward": true,
     "backward": true
    }
   ]
  },
  {
   "id": "TC9",
   "title": "Conflicting reservations",
   "description": "Dr. Ahmed already holds reservation r2 for s_e3. A second reservation r3 for s_e1 on the same day is added, then he asks for s_e3.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "double_booked(ahmed)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "can_allocate(ahmed, s_e3)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "allocate(ahmed, s_e3)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC10",
   "title": "Visitor zone closed at 19:00",
   "description": "Bilal has a valid visitor pass but arrives at 19:00. The visitor zone is open 08:00-17:00.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "authorized_driver(bilal)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "zone_open(zone_v)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "allocate(bilal, s_v1)",
     "expected": false,
     "forward": false,
     "backward": false
    }
   ]
  },
  {
   "id": "TC11",
   "title": "Reserved space requested by someone else",
   "description": "s_a5 is reserved for Zara today. Ali asks for it.",
   "checks": 3,
   "pass": true,
   "goals": [
    {
     "goal": "eligible_for_space(ali, s_a5)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "can_allocate(ali, s_a5)",
     "expected": false,
     "forward": false,
     "backward": false
    },
    {
     "goal": "can_allocate(zara, s_a5)",
     "expected": true,
     "forward": true,
     "backward": true
    }
   ]
  },
  {
   "id": "TC12",
   "title": "Inconsistent data: a student recorded as faculty",
   "description": "A data-entry error also records Ali as faculty. The Horn constraint IC4 and the DL disjointness axiom Student ⊓ Employee ⊑ ⊥ must both report it.",
   "checks": 2,
   "pass": true,
   "goals": [
    {
     "goal": "employee(ali)",
     "expected": true,
     "forward": true,
     "backward": true
    },
    {
     "goal": "student(ali)",
     "expected": true,
     "forward": true,
     "backward": true
    }
   ]
  }
 ],
 "rules": [
  {
   "id": "R01",
   "text": "person(X) :- student(X)."
  },
  {
   "id": "R02",
   "text": "person(X) :- employee(X)."
  },
  {
   "id": "R03",
   "text": "person(X) :- visitor(X)."
  },
  {
   "id": "R04",
   "text": "employee(X) :- faculty(X)."
  },
  {
   "id": "R05",
   "text": "employee(X) :- staff(X)."
  },
  {
   "id": "R06",
   "text": "permit_valid(P) :- permit_status(P, active), permit_start(P, B), permit_expiry(P, E), current_date(D), B =< D, E >= D."
  },
  {
   "id": "R07",
   "text": "permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, student_permit), student(X)."
  },
  {
   "id": "R08",
   "text": "permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, employee_permit), employee(X)."
  },
  {
   "id": "R09",
   "text": "permit_matches_role(X, P) :- has_permit(X, P), permit_class(P, visitor_pass), visitor(X)."
  },
  {
   "id": "R10",
   "text": "authorized(X, P) :- permit_matches_role(X, P), permit_valid(P)."
  },
  {
   "id": "R11",
   "text": "authorized_driver(X) :- authorized(X, P)."
  },
  {
   "id": "R12",
   "text": "zone_open(Z) :- zone_opens(Z, O), zone_closes(Z, C), current_hour(H), H >= O, H < C."
  },
  {
   "id": "R13",
   "text": "zone_access(X, Z) :- authorized(X, P), permit_class(P, C), grants(C, T), zone_type(Z, T), zone_open(Z)."
  },
  {
   "id": "R14",
   "text": "suitable_space(X, S) :- zone_access(X, Z), located_in(S, Z), owns(X, V), vehicle_type(V, VT), space_type(S, ST), fits(VT, ST)."
  },
  {
   "id": "R15",
   "text": "eligible_for_space(X, S) :- suitable_space(X, S), space_type(S, T), open_type(T)."
  },
  {
   "id": "R16",
   "text": "eligible_for_space(X, S) :- suitable_space(X, S), space_type(S, accessible), accessibility_badge(X, yes)."
  },
  {
   "id": "R17",
   "text": "space_free(S) :- space_status(S, vacant)."
  },
  {
   "id": "R18",
   "text": "holds_reservation(X, S) :- reserved_by(R, X), reserved_space(R, S), reservation_date(R, D), current_date(D)."
  },
  {
   "id": "R19",
   "text": "can_allocate(X, S) :- eligible_for_space(X, S), space_free(S)."
  },
  {
   "id": "R20",
   "text": "can_allocate(X, S) :- eligible_for_space(X, S), space_status(S, reserved), holds_reservation(X, S)."
  },
  {
   "id": "R21",
   "text": "priority(X, 3) :- person(X), accessibility_badge(X, yes)."
  },
  {
   "id": "R22",
   "text": "priority(X, 2) :- employee(X), accessibility_badge(X, no)."
  },
  {
   "id": "R23",
   "text": "priority(X, 1) :- student(X), accessibility_badge(X, no)."
  },
  {
   "id": "R24",
   "text": "priority(X, 1) :- visitor(X), accessibility_badge(X, no)."
  },
  {
   "id": "R25",
   "text": "loses(Y, S) :- requests(Y, S, TY), requests(X, S, TX), X \\= Y, can_allocate(X, S), priority(X, PX), priority(Y, PY), PX > PY."
  },
  {
   "id": "R26",
   "text": "loses(Y, S) :- requests(Y, S, TY), requests(X, S, TX), X \\= Y, can_allocate(X, S), priority(X, P), priority(Y, P), TX < TY."
  },
  {
   "id": "R27",
   "text": "double_booked(X) :- reserved_by(R1, X), reserved_by(R2, X), R1 \\= R2, reservation_date(R1, D), reservation_date(R2, D)."
  },
  {
   "id": "R28",
   "text": "allocate(X, S) :- requests(X, S, T), can_allocate(X, S), not loses(X, S), not double_booked(X)."
  }
 ],
 "network": {
  "nodes": [
   {
    "id": "ali",
    "kind": "instance"
   },
   {
    "id": "Student",
    "kind": "class"
   },
   {
    "id": "car_ali",
    "kind": "instance"
   },
   {
    "id": "p_ali",
    "kind": "instance"
   },
   {
    "id": "r1",
    "kind": "instance"
   },
   {
    "id": "Reservation",
    "kind": "class"
   },
   {
    "id": "zara",
    "kind": "instance"
   },
   {
    "id": "s_a5",
    "kind": "instance"
   },
   {
    "id": "Vehicle",
    "kind": "class"
   },
   {
    "id": "car",
    "kind": "value"
   },
   {
    "id": "ParkingPermit",
    "kind": "class"
   },
   {
    "id": "student_permit",
    "kind": "value"
   },
   {
    "id": "car_zara",
    "kind": "instance"
   },
   {
    "id": "p_zara",
    "kind": "instance"
   },
   {
    "id": "ParkingSpace",
    "kind": "class"
   },
   {
    "id": "zone_a",
    "kind": "instance"
   },
   {
    "id": "standard",
    "kind": "value"
   },
   {
    "id": "ParkingZone",
    "kind": "class"
   },
   {
    "id": "student_zone",
    "kind": "value"
   },
   {
    "id": "ned_lot",
    "kind": "instance"
   },
   {
    "id": "ParkingFacility",
    "kind": "class"
   },
   {
    "id": "Person",
    "kind": "class"
   }
  ],
  "edges": [
   {
    "s": "ali",
    "label": "instance-of",
    "t": "Student"
   },
   {
    "s": "ali",
    "label": "owns",
    "t": "car_ali"
   },
   {
    "s": "ali",
    "label": "has-a",
    "t": "p_ali"
   },
   {
    "s": "r1",
    "label": "instance-of",
    "t": "Reservation"
   },
   {
    "s": "r1",
    "label": "made-by",
    "t": "zara"
   },
   {
    "s": "r1",
    "label": "for-space",
    "t": "s_a5"
   },
   {
    "s": "car_ali",
    "label": "instance-of",
    "t": "Vehicle"
   },
   {
    "s": "car_ali",
    "label": "has-type",
    "t": "car"
   },
   {
    "s": "p_ali",
    "label": "instance-of",
    "t": "ParkingPermit"
   },
   {
    "s": "p_ali",
    "label": "has-class",
    "t": "student_permit"
   },
   {
    "s": "zara",
    "label": "instance-of",
    "t": "Student"
   },
   {
    "s": "zara",
    "label": "owns",
    "t": "car_zara"
   },
   {
    "s": "zara",
    "label": "has-a",
    "t": "p_zara"
   },
   {
    "s": "s_a5",
    "label": "instance-of",
    "t": "ParkingSpace"
   },
   {
    "s": "s_a5",
    "label": "part-of",
    "t": "zone_a"
   },
   {
    "s": "s_a5",
    "label": "has-type",
    "t": "standard"
   },
   {
    "s": "car_zara",
    "label": "instance-of",
    "t": "Vehicle"
   },
   {
    "s": "car_zara",
    "label": "has-type",
    "t": "car"
   },
   {
    "s": "p_zara",
    "label": "instance-of",
    "t": "ParkingPermit"
   },
   {
    "s": "p_zara",
    "label": "has-class",
    "t": "student_permit"
   },
   {
    "s": "zone_a",
    "label": "instance-of",
    "t": "ParkingZone"
   },
   {
    "s": "zone_a",
    "label": "has-type",
    "t": "student_zone"
   },
   {
    "s": "zone_a",
    "label": "part-of",
    "t": "ned_lot"
   },
   {
    "s": "ned_lot",
    "label": "instance-of",
    "t": "ParkingFacility"
   },
   {
    "s": "Student",
    "label": "is-a",
    "t": "Person"
   },
   {
    "s": "student_permit",
    "label": "grants",
    "t": "student_zone"
   },
   {
    "s": "car",
    "label": "fits",
    "t": "standard"
   }
  ]
 }
};
