"""Export the DL TBox and the frame ABox as OWL 2 in Turtle syntax.

Open ontology/smart_parking.ttl in Protégé and run a reasoner (HermiT or
Pellet) to compare its classification with ours.
"""

from __future__ import annotations

from itertools import count

from ..logic.description_logic import (TBOX, ABox, And, Atomic, Exists, Forall, Or,
                                       ROLES)

NS = "http://example.org/smart-parking#"


def _concept(c, blanks: list[str], counter) -> str:
    if isinstance(c, Atomic):
        return f":{c.name}"
    if isinstance(c, (And, Or)):
        key = "owl:intersectionOf" if isinstance(c, And) else "owl:unionOf"
        members = " ".join(_concept(p, blanks, counter) for p in c.parts)
        return f"[ a owl:Class ; {key} ( {members} ) ]"
    role = c.role
    prop = f"[ owl:inverseOf :{role[:-1]} ]" if role.endswith("⁻") else f":{role}"
    key = "owl:someValuesFrom" if isinstance(c, Exists) else "owl:allValuesFrom"
    return (f"[ a owl:Restriction ; owl:onProperty {prop} ; "
            f"{key} {_concept(c.filler, blanks, counter)} ]")


def to_turtle(abox: ABox | None = None) -> str:
    lines = [
        f"@prefix : <{NS}> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
        f"<{NS[:-1]}> a owl:Ontology ;",
        '    rdfs:comment "Smart Parking Access & Space Allocation, CT-351 KRR CCP. '
        'Generated by tools/build_all.py." .',
        "",
        "# Object properties",
    ]
    for role, doc in ROLES.items():
        lines.append(f':{role} a owl:ObjectProperty ; rdfs:comment "{doc}" .')
    lines.append(":locatedIn a owl:FunctionalProperty .")
    lines += ["", "# Classes"]
    names = set()
    for ax in TBOX:
        for side in (ax.left, ax.right):
            stack = [side]
            while stack:
                c = stack.pop()
                if isinstance(c, Atomic):
                    names.add(c.name)
                elif isinstance(c, (And, Or)):
                    stack.extend(c.parts)
                else:
                    stack.append(c.filler)
    for n in sorted(names):
        lines.append(f":{n} a owl:Class .")
    lines += ["", "# Axioms"]
    counter = count(1)
    for ax in TBOX:
        left = _concept(ax.left, [], counter)
        right = _concept(ax.right, [], counter)
        pred = {"subsumption": "rdfs:subClassOf", "equivalence": "owl:equivalentClass",
                "disjoint": "owl:disjointWith"}[ax.kind]
        lines.append(f"# {ax.aid}: {ax}")
        lines.append(f"{left} {pred} {right} .")
    if abox is not None:
        lines += ["", "# Individuals"]
        for ind in sorted(abox.concepts):
            types = ", ".join(f":{c}" for c in sorted(abox.concepts[ind]))
            lines.append(f":{ind} a owl:NamedIndividual, {types} .")
        for role, a, b in sorted(abox.roles):
            lines.append(f":{a} :{role} :{b} .")
        inds = " ".join(f":{i}" for i in sorted(abox.concepts))
        lines.append(f"[ a owl:AllDifferent ; owl:distinctMembers ( {inds} ) ] .")
    return "\n".join(lines) + "\n"
