"""Write the knowledge base as an SWI-Prolog program.

The file is generated from the same facts and rules the Python engines use,
so Prolog can be used as an independent check: the answers to
?- allocate(X, S). in SWI-Prolog must equal the allocations the Python
forward chainer derives.
"""

from __future__ import annotations

from ..core.kb import KnowledgeBase
from ..core.terms import format_atom
from ..knowledge_base.facts import grouped
from ..knowledge_base.scenarios import Scenario


def to_prolog(kb: KnowledgeBase, scenario: Scenario) -> str:
    signatures = sorted({(f[0], len(f) - 1) for f in kb.facts}
                        | {(r.head[0], len(r.head) - 1) for r in kb.rules}
                        | {(l.predicate, len(l.atom) - 1) for r in kb.rules for l in r.body
                           if l.kind != "builtin"})
    sig_text = ", ".join(f"{p}/{n}" for p, n in signatures)
    out = [
        "/*  Smart Parking Access & Space Allocation Reasoning System",
        "    CT-351 Knowledge Representation & Reasoning, NED University",
        "",
        "    Generated by tools/build_all.py from krr/knowledge_base. Edit the",
        "    Python sources, not this file.",
        f"    Scenario: {scenario.key} ({scenario.title})",
        "",
        "    Run:   swipl prolog/smart_parking.pl",
        "    Try:   ?- allocate(X, S).",
        "           ?- can_allocate(fatima, S).",
        "           ?- authorized_driver(usman).",
        "           ?- show_allocations.",
        "           ?- consistent.",
        "*/",
        "",
        f":- dynamic {sig_text}.",
        f":- discontiguous {sig_text}.",
        "",
    ]
    for title, rows in grouped(kb.facts):
        out.append(f"% ---- Facts: {title} " + "-" * max(4, 60 - len(title)))
        out += rows
        out.append("")
    out.append("% ---- Rules (Horn clauses) " + "-" * 40)
    group = None
    for rule in kb.rules:
        if rule.group != group:
            group = rule.group
            out.append(f"\n% {group}")
        out.append(f"% {rule.rid}: {rule.natural}")
        out.append(rule.to_prolog())
    out.append("")
    out.append("% ---- Integrity constraints (denial clauses) " + "-" * 22)
    out.append("% A constraint is violated when its body can be proved.")
    for c in kb.constraints:
        body = ", ".join(l.to_prolog() for l in c.body)
        out.append(f"% {c.cid}: {c.natural}")
        out.append(f"violation({c.cid.lower()}) :- {body}.")
    out += [
        "",
        "% ---- Helpers " + "-" * 50,
        "consistent :- \\+ violation(_).",
        "show_allocations :-",
        "    forall(allocate(X, S), format(\"allocate(~w, ~w)~n\", [X, S])).",
        "",
    ]
    return "\n".join(out)
